import Hero from "@/components/Hero";
import Instagram from "@/components/Instagram";
import Slider from "@/components/Slider";
import { SliderData } from "@/components/SliderData";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mansa Nzinga Productions</title>
        <meta name="description" content="Generated by kanjī."></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Mansa Nzinga Productions"
        message="Unveiling African stories. Where experiences meet cinema, and culture finds a voice."
      />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
